<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">replaceAllFromString</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFNYXAgcGlwZWxpbmVNYXAgPSBuZXcgSURhdGFNYXAocGlwZWxpbmUpOw0KU3RyaW5nIGlu
cHV0U3RyaW5nID0gcGlwZWxpbmVNYXAuZ2V0QXNTdHJpbmcoImlucHV0U3RyaW5nIik7DQpTdHJp
bmcgcmVnZXggPSBwaXBlbGluZU1hcC5nZXRBc1N0cmluZygicmVnZXgiKTsNClN0cmluZyBzdHJp
bmdUb1JlcGxhY2UgPSBwaXBlbGluZU1hcC5nZXRBc1N0cmluZygic3RyaW5nVG9SZXBsYWNlIik7
DQoNCmlmIChzdHJpbmdUb1JlcGxhY2UgPT0gbnVsbCkgew0KCXN0cmluZ1RvUmVwbGFjZSA9ICIi
Ow0KfQ0KDQpTdHJpbmcgb3V0cHV0U3RyaW5nID0gbnVsbDsNCg0KaWYgKGlucHV0U3RyaW5nICE9
IG51bGwgJiYgISIiLmVxdWFscyhpbnB1dFN0cmluZy50cmltKCkpICYmIHJlZ2V4ICE9IG51bGwg
JiYgISIiLmVxdWFscyhyZWdleC50cmltKCkpKSB7DQoJb3V0cHV0U3RyaW5nID0gaW5wdXRTdHJp
bmcucmVwbGFjZUFsbChyZWdleCwgc3RyaW5nVG9SZXBsYWNlKTsNCn0NCg0KcGlwZWxpbmVNYXAu
cHV0KCJvdXRwdXRTdHJpbmciLCBvdXRwdXRTdHJpbmcpOw0KCQ==</value>
</Values>
