<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">isValidDateTimePattern</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFNYXAgcGlwZWxpbmVNYXAgPSBuZXcgSURhdGFNYXAocGlwZWxpbmUpOw0KU3RyaW5nIGRh
dGVQYXR0ZXJuID0gcGlwZWxpbmVNYXAuZ2V0QXNTdHJpbmcoInBhdHRlcm4iKTsNClN0cmluZyBk
YXRlVGltZSA9IHBpcGVsaW5lTWFwLmdldEFzU3RyaW5nKCJkYXRlVGltZSIpOw0KDQpTdHJpbmcg
bWF0Y2hlcyA9ICJmYWxzZSI7DQoNCmlmIChkYXRlUGF0dGVybiAhPSBudWxsICYmICFkYXRlUGF0
dGVybi50cmltKCkuZXF1YWxzKCIiKSANCgkJJiYgZGF0ZVRpbWUgIT0gbnVsbCAmJiAhZGF0ZVRp
bWUudHJpbSgpLmVxdWFscygiIikpIHsNCgkNCglTaW1wbGVEYXRlRm9ybWF0IGZvcm1hdCA9IG5l
dyBTaW1wbGVEYXRlRm9ybWF0KGRhdGVQYXR0ZXJuKTsNCglmb3JtYXQuc2V0TGVuaWVudChmYWxz
ZSk7DQoJDQoJdHJ5IHsNCgkJZm9ybWF0LnBhcnNlKGRhdGVUaW1lKTsNCgkJbWF0Y2hlcyA9ICJ0
cnVlIjsNCgl9IGNhdGNoIChQYXJzZUV4Y2VwdGlvbiBwZXgpIHsNCgkJbWF0Y2hlcyA9ICJmYWxz
ZSI7DQoJfQ0KfQ0KcGlwZWxpbmVNYXAucHV0KCJtYXRjaGVzIiwgbWF0Y2hlcyk7</value>
</Values>
